version: '3.8'

services:
  nginx:
    image: nginx:1.28.0-alpine
    volumes:
      - static_volume:/home/ubc_voc_website/staticfiles
      - .nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8082:80
    depends_on:
      - web
  
  web:
    build:
      context: ./ubc_voc_website
      dockerfile: Dockerfile.prod
    image: ubc_voc_website
    command: gunicorn ubc_voc_website.wsgi:application --bind 0.0.0.0:8000 --access-logfile /home/ubc_voc_website/web/logs/gunicorn_access.log
    volumes:
      - static_volume:/home/ubc_voc_website/staticfiles
    expose:
      -8000
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=ubc_voc_website.settings.production
      - DJANGO_ALLOWED_HOSTS=test-ubc-voc.com
      - DATABASE_NAME=${DB}
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_HOST=db

  db:
    image: postgres:18-alpine
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes: 
      - .backups:/backups
    depends_on:
      - db
    expose:
      - 81
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${DB}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=3
      - BACKUP_KEEP_WEEKS=2
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=81

